### ISSUE TITLE
'parse_input' function incorrectly evaluates expressions containing 'x'

### ISSUE THREAD

**Issue by Njmcq** [4rtemis-4rrow/Pythagoras#1]
## Description
The 'parse_input' function in the calculator incorrectly evaluates expressions containing 'x' due to the use of 'eval()' with a fixed value of x=1.

## Steps to Reproduce
1. Run the program
2. Enter the following expressions:
- x + 2
- 2*x
- x^2

## Expected Behaviour
The calculator should treat 'x' as a symbol and return symbolic expressions:
- 'x + 2' should return 'x + 2'
- '2*x' should return '2*x'
- 'x^2' should return 'x^2'

Even if the user attempts to modify the value of 'x' (e.g. x = 4), 'x' remains equivalent to 1.

## Actual Behaviour
Instead, the calculator evaluates expressions with x=1:
- 'x + 2' returns 3
- '2*x' returns 2
- 'x^2' returns 3

**Comment by 4rtemis-4rrow** [comment]
fixed

uppercase letters are now treated as functions, lowercase letters are treated as variables

if a variable hasn't been assigned value, using it will simply return an expression, eg

```
> x + 2
Result: x + 2
```

once it's assigned a value, it will be replaced with that value, and the expression would be evaluated, a variable's value can be cleared by `clear <var>`
